# Generated by Django 5.1.dev20240328164504 on 2024-03-29 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='last_updated_by',
            field=models.ForeignKey(db_column='last_updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_actions_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
